TWIST
TWIST

diff --git a/twist b/twist
--- a/twist
+++ b/twist
@@ -165,6 +165,31 @@ function uninstall_twist(){
     rm -fr /usr/local/share/doc/shadowsocks-libev
     rm -fr /etc/shadowsocks-libev
     rm -f /etc/init.d/shadowsocks
+    [ -e /etc/twistbackup/sysctl.conf ] && { cp -f "/etc/twistbackup/sysctl.conf" "/etc/sysctl.conf"; sysctl -e -p; }
+    [ -e /etc/twistbackup/limits.conf ] && cp -f "/etc/twistbackup/limits.conf" "/etc/security/limits.conf"
+    [ -e /etc/twistbackup/login ] && cp -f "/etc/twistbackup/login" "/etc/pam.d/login"
+    [ -e /etc/twistbackup/iptables.rules ] && { cp -f "/etc/twistbackup/iptables.rules" "/etc/iptables.rules"; iptables-restore < /etc/iptables.rules; }
+    [ -e /etc/twistbackup/rules.v6 ] && { cp -f "/etc/twistbackup/rules.v6" "/etc/iptables/rules.v6"; iptables-restore < /etc/iptables/rules.v6; }
+    if [ -e /etc/ip6tables.rules ]; then
+        [ -e "/etc/twistbackup/rules.v6 ] && cp -f "/etc/twistbackup/rules.v6" "/etc/ip6tables.rules"
+    fi
+    if [ -e /etc/twistbackup/iptablesload ]; then
+        cp -f "/etc/twistbackup/iptablesload" "/etc/network/if-pre-up.d/iptablesload"
+    else
+        rm -f /etc/network/if-pre-up.d/iptablesload
+    fi
+    if [ -e /etc/twistbackup/ip6tablesload ]; then
+        cp -f "/etc/twistbackup/ip6tablesload" "/etc/network/if-pre-up.d/ip6tablesload"
+    else
+        rm -f /etc/network/if-pre-up.d/ip6tablesload
+    fi
+    [ -e /etc/twistbackup/jail.local ] && cp -f "/etc/twistbackup/jail.local" "/etc/fail2ban/jail.local"
+    [ -e /etc/twistbackup/twist ] && cp -f "/etc/twistbackup/twist" "/usr/bin/twist"
+    [ -e /etc/twistbackup/.htaccess ] && cp -f "/etc/twistbackup/.htaccess" "/var/www/html/.htaccess"
+    [ -e /etc/twistbackup/index.html ] && cp -f "/etc/twistbackup/index.html" "/var/www/html/index.html"
+    rm -fr /etc/twistbackup
+    service fail2ban restart
+    systemctl restart apache2
     ldconfig
     clear
     twist
@@ -319,7 +344,7 @@ function installlibs(){
     elif [ "$packagemanagertype" = "y" ]; then
         yum -y update || { echo ""; echo -e "# [\033[31;1mCannot Update Source, Please Check Your Network or Errors Noticed! \033[0m]"; echo ""; exit 1; }
         yum -y upgrade || { echo ""; echo -e "# [\033[31;1mCannot Upgrade Source, Please Check Your Network or Errors Noticed! \033[0m]"; echo ""; exit 1; }
-        [ ! -f /etc/yum.repos.d/epel.repo ] && { yum -y install epel-release yum-utils || { echo -e "# [\033[31;1mCannot Add EPEL repository. Aborting! \033[0m]"; exit 1; }; }
+        [ -e /etc/yum.repos.d/epel.repo ] || { yum -y install epel-release yum-utils || { echo -e "# [\033[31;1mCannot Add EPEL repository. Aborting! \033[0m]"; exit 1; }; }
         yum -y install wget gawk grep curl sed git gcc swig gettext-devel autoconf automake make libtool pcre-devel perl-devel cpio xmlto asciidoc fail2ban net-tools bind-utils rng-tools expat-devel openssl-devel zlib-devel libev-devel c-ares-devel python-devel python-setuptools python-pip
         [ "$?" != "0" ] && { echo ""; echo -e "# [\033[31;1mCannot Install Dependencies, Please Check Your Network or Errors Noticed! \033[0m]"; echo ""; exit 1; }
         [ "$FWS" = "enable" ] && { yum -y install httpd || { echo ""; echo -e "# [\033[31;1mCannot Install Apache as Fake Web Server, Please Check Your Network or Errors Noticed! \033[0m]"; echo ""; exit 1; }; }
@@ -550,7 +575,8 @@ COMMIT
 EOF
         [ -e /etc/iptables/rules.v6 ] && cp -f "/etc/iptables/rules.v6" "/etc/twistbackup/rules.v6"
         [ -e /etc/iptables/rules.v6 ] && cp -f "/etc/iptables/rules.v6" "/etc/twistbackup/rules.v6.old-${date}"
-        [ -e /etc/iptables/rules.v6 ] && cp -f "/etc/ip6tables.rules" "/etc/iptables/rules.v6"
+        [ -e /etc/ip6tables.rules ] && cp -f "/etc/ip6tables.rules" "/etc/iptables/rules.v6"
+        iptables-save > "/etc/iptables.rules"
         [ -e /etc/network/if-pre-up.d/iptablesload ] && cp -f "/etc/network/if-pre-up.d/iptablesload" "/etc/twistbackup/iptablesload"
         [ -e /etc/network/if-pre-up.d/iptablesload ] && cp -f "/etc/network/if-pre-up.d/iptablesload" "/etc/twistbackup/iptablesload.old-${date}"
         [ -d /etc/network/if-pre-up.d ] || mkdir -p /etc/network/if-pre-up.d
