TWIST
TWIST

diff --git a/twist b/twist
--- a/twist
+++ b/twist
@@ -239,8 +239,8 @@ function detectsystem(){
             yum -y update || { echo ""; echo -e "# [\033[31;1mCannot Update Source, Please Check Your Network or Errors Noticed! \033[0m]"; echo ""; exit 1; }
             yum -y install gawk net-tools bind-utils curl || { echo ""; echo -e "# [\033[31;1mCannot Install Dependencies, Please Check Your Network or Errors Noticed! \033[0m]"; echo ""; exit 1; }
         else
-            pacman -Syu --noconfirm || { echo ""; echo -e "# [\033[31;1mCannot Update Source, Please Check Your Network or Errors Noticed! \033[0m]"; echo ""; exit 1; }
-            pacman -S --noconfirm gawk net-tools curl || { echo ""; echo -e "# [\033[31;1mCannot Install Dependencies, Please Check Your Network or Errors Noticed! \033[0m]"; echo ""; exit 1; }
+            pacman -Syy --noconfirm || { echo ""; echo -e "# [\033[31;1mCannot Update Source, Please Check Your Network or Errors Noticed! \033[0m]"; echo ""; exit 1; }
+            pacman -Syu --noconfirm gawk net-tools curl || { echo ""; echo -e "# [\033[31;1mCannot Install Dependencies, Please Check Your Network or Errors Noticed! \033[0m]"; echo ""; exit 1; }
         fi
         clear
     fi
@@ -635,7 +635,7 @@ EOF
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Shadowsocks-libev
-# Description:       Start, Stop or Restart Shadowsocks-libev Server
+# Description:       Shadowsocks-libev Service
 ### END INIT INFO
 
 sysctl -q -p
