testing
testing

diff --git a/twist b/twist
--- a/twist
+++ b/twist
@@ -55,7 +55,6 @@ function disableselinux(){
 
 function defaultvalue(){
     BBR="enable"
-    PORT="443"
     ETH="eth0"
     IPREGEX="^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"
 }
@@ -133,6 +132,12 @@ function getip(){
             echo ""
         fi
     fi
+    sslibevport="\"0.0.0.0\""
+    if [ -f /proc/net/if_inet6 ]; then
+       PUBLICIPv6=`ifconfig | grep -E '(Link|inet6)'|grep -v "Scope:Link"`
+       [ -z "$PUBLICIPv6" ] && ipv6=false
+       sslibevport="[\"[::0]\",\"0.0.0.0\"]"
+    fi
 }
 
 function installlibs(){
@@ -143,8 +148,7 @@ function installlibs(){
 	yum -y install epel-release
         yum list installed epel-release >/dev/null 2>&1
         [ "$?" != "0" ] && { echo -e "# [\033[31;1mCannot Add EPEL repository! Aborting!\033[0m]"; exit 1; }
-        yum -y install unzip openssl-devel gcc swig python python-devel python-setuptools autoconf libtool libevent automake make curl curl-devel zlib-devel perl perl-devel cpio expat-devel gettext-devel || { echo ""; echo -e "# [\033[31;1mCannot Install Libs! Please Check Your Network!\033[0m]"; echo ""; exit 1; }      
-	yum -y install radvd || { echo ""; echo -e "# [\033[31;1mCannot Install Radvd! Please Check Your Network!\033[0m]"; echo ""; exit 1; }
+        yum -y install unzip openssl-devel gcc swig python python-devel python-setuptools autoconf libtool libevent automake make curl curl-devel zlib-devel perl perl-devel cpio expat-devel gettext-devel || { echo ""; echo -e "# [\033[31;1mCannot Install Libs! Please Check Your Network!\033[0m]"; echo ""; exit 1; }
         if grep -qs "release 6" /etc/redhat-release; then
             yum -y install iptables-ipv6
             yum -y remove libevent-devel
@@ -157,7 +161,6 @@ function installlibs(){
         apt-get -yq install wget dnsutils || { echo ""; echo -e "# [\033[31;1mCannot Install Libs! Please Check Your Network!\033[0m]"; echo ""; exit 1; }
         apt-get -yq install gawk grep sed net-tools git || { echo ""; echo -e "# [\033[31;1mCannot Install Libs! Please Check Your Network!\033[0m]"; echo ""; exit 1; }
 	apt-get -yq install python python-dev python-pip python-m2crypto curl wget unzip gcc swig automake make perl cpio build-essential || { echo ""; echo -e "# [\033[31;1mCannot Install Libs! Please Check Your Network!\033[0m]"; echo ""; exit 1; }
-        apt-get -yq install radvd || { echo ""; echo -e "# [\033[31;1mCannot Install Radvd! Please Check Your Network!\033[0m]"; echo ""; exit 1; }
     fi
 }
 
@@ -213,41 +216,41 @@ function installbbr(){
 }
 
 function installssr(){
-   cd `pwd`
-   wget -t 3 -T 30 -nv -O manyuser.zip https://github.com/shadowsocksr/shadowsocksr/archive/manyuser.zip
-   [ "$?" != "0" ] && { echo ""; echo -e "# [\033[31;1mCannot download shadowsocksr source. Aborting.\033[0m]"; echo ""; exit 1; }
-   unzip -q -o manyuser.zip
-   mv shadowsocksr-manyuser/shadowsocks /usr/local/
+   installpath=`pwd`
+   cd $installpath
    libsodiumver=`wget -qO- https://download.libsodium.org/libsodium/releases/ | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | cut -d'.' -f1,2,3 | sort -V | tail -1`
    wget -t 3 -T 30 -nv -O libsodium-${libsodiumver}.tar.gz https://download.libsodium.org/libsodium/releases/libsodium-${libsodiumver}.tar.gz
-   [ "$?" != "0" ] && { echo ""; echo -e "# [\033[31;1mCannot download libsodium source. Aborting.\033[0m]"; echo ""; exit 1; }
-   tar -zxvf libsodium-${libsodiumver}.tar.gz
+   [ "$?" != "0" ] && { echo ""; echo -e "# [\033[31;1mCannot Download Libsodium Source. Aborting.\033[0m]"; echo ""; exit 1; }
+   tar zxf libsodium-${libsodiumver}.tar.gz
    cd libsodium-${libsodiumver}
-   ./configure --prefix=/usr && make && make install || { echo ""; echo －e "# [\033[31;1mLibsodium failed to build. Aborting.\033[0m]"; echo ""; exit 1; }  
-   rm -rf manyuser.zip shadowsocksr-manyuser libsodium-${libsodiumver}.tar.gz libsodium-${libsodiumver}.tar.gz
+   ./configure --prefix=/usr && make && make install || { echo ""; echo －e "# [\033[31;1mLibsodium Failed to Build. Aborting.\033[0m]"; echo ""; exit 1; }
+   ldconfig
+   cd $installpath
+   shadowsocksver=$(wget -qO- https://api.github.com/repos/shadowsocks/shadowsocks-libev/releases/latest | grep 'tag_name' | cut -d\" -f4)
+   shadowsockslibev="shadowsocks-libev-$(echo ${shadowsocksver} | sed -e 's/^[a-zA-Z]//g')"
+   wget -t 3 -T 30 -nv -O ${shadowsockslibev}.tar.gz https://github.com/shadowsocks/shadowsocks-libev/releases/download/${shadowsocksver}/${shadowsockslibev}.tar.gz
+   [ "$?" != "0" ] && { echo ""; echo -e "# [\033[31;1mCannot Download Shadowsocks-libev Source. Aborting.\033[0m]"; echo ""; exit 1; }
+   tar zxf ${shadowsockslibev}.tar.gz
+   cd $shadowsockslibev
+   ./configure && make && make install || { echo ""; echo －e "# [\033[31;1mShadowsocks-libev Failed to Build. Aborting.\033[0m]"; echo ""; exit 1; }
+   cd $installpath && rm -rf ${shadowsockslibev}.tar.gz ${shadowsockslibev} libsodium-${libsodiumver}.tar.gz libsodium-${libsodiumver}.tar.gz
 }
 
 function configssr(){
     date="$(date +%Y-%m-%d-%H:%M:%S)"
     PASSWORD="$(< /dev/urandom tr -dc 'A-HJ-NPR-Za-km-z2-9' | head -c 16)"
-    cat > /etc/shadowsocks.json <<EOF
+    if [ ! -d /etc/shadowsocks-libev ]; then
+        mkdir -p /etc/shadowsocks-libev
+    fi
+    cat > /etc/shadowsocks-libev/config.json<<-EOF
 {
-    "server":"0.0.0.0",
-    "server_ipv6":"::",
+    "server":${sslibevport},
     "server_port":443,
     "local_address":"127.0.0.1",
     "local_port":1080,
     "password":"${PASSWORD}",
-    "timeout":120,
-    "method":"chacha20-ietf",
-    "protocol":"origin",
-    "protocol_param":"",
-    "obfs":"plain",
-    "obfs_param":"",
-    "redirect":"",
-    "dns_ipv6":true,
-    "fast_open":true,
-    "workers":1
+    "timeout":600,
+    "method":"chacha20-ietf"
 }
 EOF
     if ! grep -qs "Twist" /etc/sysctl.conf; then
@@ -349,20 +352,13 @@ iptables-restore < /etc/iptables.rules
 exit 0
 EOF
     fi
-    if ! grep -qs "Twist" /etc/rc.local; then
-       /bin/cp -f /etc/rc.local "/etc/rc.local.old-$date" 2>/dev/null
-       sed --follow-symlinks -i -e '/^exit 0/d' /etc/rc.local
-       cat >> /etc/rc.local <<EOF
 
-# Twist Configs
-iptables -I FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
-if [ -z `ps -ef | grep -v grep | grep -i "/usr/local/shadowsocks/server.py" | awk '{print $2}'` ]; then
-    /usr/local/shadowsocks/server.py -c /etc/shadowsocks.json -d start
-fi
-echo 1 > /proc/sys/net/ipv4/ip_forward
-exit 0
-EOF
-    fi
+    chmod +x /etc/init.d/shadowsocks
+    chkconfig --add shadowsocks
+    chkconfig shadowsocks on
+
+
+ 
 }
 
 function startservices(){
@@ -376,6 +372,7 @@ function startservices(){
     else
         iptables-restore < "$IPTFILE"
     fi
+    
     if [ -z `ps -ef | grep -v grep | grep -i "/usr/local/shadowsocks/server.py" | awk '{print $2}'` ]; then
         /usr/local/shadowsocks/server.py -c /etc/shadowsocks.json -d start
     fi
